version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:448472727005:task-definition/My-Task:3"
        LoadBalancerInfo:
          ContainerName: "CICD"
          ContainerPort: 8080
# Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-09be93c268d94b2ef","subnet-030ac53c9b6fd5c36","subnet-01da72fbf9732ecf7"]
            SecurityGroups: ["sg-053b66c4adca0432a"]
            AssignPublicIp: "ENABLED"
        CapacityProviderStrategy:
          - Base: 1
            CapacityProvider: "FARGATE_SPOT"
            Weight: 2
          - Base: 0
            CapacityProvider: "FARGATE"
            Weight: 1
